let name = "Stephany";
console.log(name);
let age = 19;
console.log(age);
let number1 = 11;
let number2 = 22;
console.log(number1);
console.log(number2);
let sum = number1 + number2;
console.log(sum);
let difference = number2 - number1;
console.log(difference);
let product = number2 * number1;
console.log(product);
let modular = number2 % number1;
console.log(modular);
let itstudent = true;
console.log(itstudent);
let num=100;
console.log(typeof num);
let str="Hello";
console.log(typeof str);
